name: duplicati
services:
  duplicati:
    container_name: duplicati
    image: linuxserver/duplicati:2.1.0
    user: 0:0
    environment:
      PGID: 0
      PUID: 0
      TZ: $TZ
      SETTINGS_ENCRYPTION_KEY: '$default_pwd'
      DUPLICATI__WEBSERVICE_PASSWORD: '$default_pwd'
    expose:
      - 8200
    cpu_shares: 10
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 64M
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/duplicati/config
        target: /config
      - type: bind
        source: /DATA/
        target: /source/DATA

x-casaos:
  architectures:
    - amd64
    - arm64
  main: duplicati
  author: Yundera Team
  category: Cloud
  description:
    en_us: Duplicati is a free, open source, backup client that securely stores encrypted, incremental, compressed backups on cloud storage services and remote file servers.
    zh_cn: Duplicati是一个免费的开源备份客户端，它可以安全地存储加密的、增量的、压缩的备份文件到云存储服务和远程文件服务器。
    fr_fr: Duplicati est un client de sauvegarde gratuit et open source qui stocke de manière sécurisée des sauvegardes chiffrées, incrémentales et compressées sur des services de stockage dans le cloud et des serveurs de fichiers distants.
    ko_kr: Duplicati는 클라우드 스토리지 서비스와 원격 파일 서버에 암호화되고 증분적이며 압축된 백업을 안전하게 저장하는 무료 오픈 소스 백업 클라이언트입니다.
    es_es: Duplicati es un cliente de copia de seguridad gratuito y de código abierto que almacena de forma segura copias de seguridad cifradas, incrementales y comprimidas en servicios de almacenamiento en la nube y servidores de archivos remotos.
    ar_sa: Duplicati هو عميل احتياطي مفتوح المصدر مجاني ، يخزن بشكل آمن ومشفر ، مضغوط ، متزايد ، مضغوط على خدمات تخزين السحابة وخوادم الملفات البعيدة.
    de_de: Duplicati ist ein kostenloser Open-Source-Backup-Client, der verschlüsselte, inkrementelle, komprimierte Backups sicher auf Cloud-Speicherdiensten und Remote-Dateiservern speichert.
    hu_hu: A Duplicati egy ingyenes és nyílt forráskódú biztonsági másolat kliens, amely biztonságosan tárolja az inkrementálisan, tömörített módon titkosított biztonsági mentéseket felhőtárhelyeken és távoli fájl szervereken.
    it_it: Duplicati è un client di backup gratuito e open source che memorizza in modo sicuro backup crittografati, incrementali e compressi su servizi di archiviazione in cloud e server file remoti.
    ru_ru: Duplicati - это бесплатный клиент резервного копирования с открытым исходным кодом, который безопасно хранит зашифрованные, инкрементальные, сжатые резервные копии на облачных службах хранения и удаленных файловых серверах.
    pl_pl: Duplicati to darmowy klient kopii zapasowych open source, który bezpiecznie przechowuje zaszyfrowane, inkrementalne, skompresowane kopie zapasowe na usługach chmurowych i zdalnych serwerach plików.
    pt_br: Duplicati é um cliente de backup gratuito e de código aberto que armazena de forma segura backups criptografados, incrementais e compactados em serviços de armazenamento em nuvem e servidores de arquivos remotos.
    sv_se: Duplicati är en gratis, öppen källkod, backup-klient som säkert lagrar krypterade, inkrementella, komprimerade säkerhetskopior på molntjänster och fjärrfiler.
    uk_ua: Duplicati - це безкоштовний клієнт резервного копіювання з відкритим вихідним кодом, який безпечно зберігає зашифровані, інкрементні, стиснені резервні копії на хмарних службах зберігання та віддалених файлових серверах.
  developer: Duplicati Team
  icon: https://cdn.jsdelivr.net/gh/Yundera/AppStore@main/Apps/Duplicati/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/Yundera/AppStore@main/Apps/Duplicati/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/Yundera/AppStore@main/Apps/Duplicati/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/Yundera/AppStore@main/Apps/Duplicati/screenshot-3.png
  tagline:
    en_us: Upload, delete, preview, rename, edit and share your files.
    zh_cn: 上传，删除，预览，重命名，编辑和共享您的文件。
    ar_sa: قم بتحميل، حذف، معاينة، إعادة تسمية، تحرير ومشاركة ملفاتك.
    de_de: Hochladen, Löschen, Vorschau, Umbenennen, Bearbeiten und Freigeben Ihrer Dateien.
    es_es: Subir, eliminar, previsualizar, renombrar, editar y compartir sus archivos.
    fr_fr: Télécharger, supprimer, prévisualiser, renommer, modifier et partager vos fichiers.
    hu_hu: Töltsön fel, törölje, előnézze, átnevezze, szerkessze és ossza meg fájljait.
    it_it: Carica, elimina, anteprima, rinomina, modifica e condividi i tuoi file.
    ru_ru: Загрузите, удалите, просмотрите, переименуйте, отредактируйте и поделитесь своими файлами.
    pl_pl: Prześlij, usuń, podgląd, zmień nazwę, edytuj i udostępnij swoje pliki.
    pt_br: Faça upload, exclua, visualize, renomeie, edite e compartilhe seus arquivos.
    sv_se: Ladda upp, ta bort, förhandsgranska, byt namn, redigera och dela dina filer.
    uk_ua: Завантажте, видаліть, перегляньте, перейменуйте, відредагуйте і поділіться своїми файлами.
  thumbnail: https://cdn.jsdelivr.net/gh/Yundera/AppStore@main/Apps/Duplicati/thumbnail.png
  tips:
    before_install:
      en_us: |
        Default Password : `$default_pwd`
        Your Files will appear in the `Computer/source/DATA` directory inside duplicati source panel (3).
  title:
    en_us: Duplicati
  index: /
  webui_port: 8200
